# Generated by Django 4.1.5 on 2023-03-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='validate',
            field=models.TextField(default='Unverified'),
        ),
    ]
